version = 0.1
[default.deploy.parameters]
stack_name = "SFTokenRefresh"
resolve_s3 = true
s3_prefix = "SFTokenRefresh"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "SalesforceClientId=\"\" SalesforceClientSecret=\"\" SalesforceRefreshToken=\"\""
